#############################################################################
# Makefile for building: rc
# Generated by qmake (2.01a) (Qt 4.8.1) on: Tue Apr 24 21:50:15 2012
# Project:  rc.pro
# Template: app
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile rc.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4 -Itemp/unix-debug -Itemp/unix-debug
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib/i386-linux-gnu -lQtGui -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake-qt4
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = temp/unix-debug/

####### Files

SOURCES       = main.cpp \
		Window.cpp \
		Peer.cpp \
		Net.cpp \
		Settings.cpp \
		Input.cpp \
		InputDialog.cpp \
		Inputs.cpp temp/unix-debug/moc_Window.cpp \
		temp/unix-debug/moc_Peer.cpp \
		temp/unix-debug/moc_Net.cpp \
		temp/unix-debug/moc_Settings.cpp \
		temp/unix-debug/moc_InputAxisWidget.cpp \
		temp/unix-debug/moc_InputBtnWidget.cpp \
		temp/unix-debug/moc_Input.cpp \
		temp/unix-debug/moc_InputDialog.cpp \
		temp/unix-debug/moc_Inputs.cpp
OBJECTS       = temp/unix-debug/main.o \
		temp/unix-debug/Window.o \
		temp/unix-debug/Peer.o \
		temp/unix-debug/Net.o \
		temp/unix-debug/Settings.o \
		temp/unix-debug/Input.o \
		temp/unix-debug/InputDialog.o \
		temp/unix-debug/Inputs.o \
		temp/unix-debug/moc_Window.o \
		temp/unix-debug/moc_Peer.o \
		temp/unix-debug/moc_Net.o \
		temp/unix-debug/moc_Settings.o \
		temp/unix-debug/moc_InputAxisWidget.o \
		temp/unix-debug/moc_InputBtnWidget.o \
		temp/unix-debug/moc_Input.o \
		temp/unix-debug/moc_InputDialog.o \
		temp/unix-debug/moc_Inputs.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		rc.pro
QMAKE_TARGET  = rc
DESTDIR       = 
TARGET        = rc

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): temp/unix-debug/ui_Window.h temp/unix-debug/ui_InputAxisWidget.h temp/unix-debug/ui_InputBtnWidget.h temp/unix-debug/ui_InputDialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: rc.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/declarative_debug.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/i386-linux-gnu/libQtGui.prl \
		/usr/lib/i386-linux-gnu/libQtNetwork.prl \
		/usr/lib/i386-linux-gnu/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile rc.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_phonon.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/declarative_debug.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/i386-linux-gnu/libQtGui.prl:
/usr/lib/i386-linux-gnu/libQtNetwork.prl:
/usr/lib/i386-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile rc.pro

dist: 
	@$(CHK_DIR_EXISTS) temp/unix-debug/rc1.0.0 || $(MKDIR) temp/unix-debug/rc1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) temp/unix-debug/rc1.0.0/ && $(COPY_FILE) --parents Window.h Peer.h Net.h Settings.h InputAxisWidget.h InputBtnWidget.h Input.h InputDialog.h Inputs.h temp/unix-debug/rc1.0.0/ && $(COPY_FILE) --parents main.cpp Window.cpp Peer.cpp Net.cpp Settings.cpp Input.cpp InputDialog.cpp Inputs.cpp temp/unix-debug/rc1.0.0/ && $(COPY_FILE) --parents Window.ui InputAxisWidget.ui InputBtnWidget.ui InputDialog.ui temp/unix-debug/rc1.0.0/ && (cd `dirname temp/unix-debug/rc1.0.0` && $(TAR) rc1.0.0.tar rc1.0.0 && $(COMPRESS) rc1.0.0.tar) && $(MOVE) `dirname temp/unix-debug/rc1.0.0`/rc1.0.0.tar.gz . && $(DEL_FILE) -r temp/unix-debug/rc1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: temp/unix-debug/moc_Window.cpp temp/unix-debug/moc_Peer.cpp temp/unix-debug/moc_Net.cpp temp/unix-debug/moc_Settings.cpp temp/unix-debug/moc_InputAxisWidget.cpp temp/unix-debug/moc_InputBtnWidget.cpp temp/unix-debug/moc_Input.cpp temp/unix-debug/moc_InputDialog.cpp temp/unix-debug/moc_Inputs.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) temp/unix-debug/moc_Window.cpp temp/unix-debug/moc_Peer.cpp temp/unix-debug/moc_Net.cpp temp/unix-debug/moc_Settings.cpp temp/unix-debug/moc_InputAxisWidget.cpp temp/unix-debug/moc_InputBtnWidget.cpp temp/unix-debug/moc_Input.cpp temp/unix-debug/moc_InputDialog.cpp temp/unix-debug/moc_Inputs.cpp
temp/unix-debug/moc_Window.cpp: Window.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Window.h -o temp/unix-debug/moc_Window.cpp

temp/unix-debug/moc_Peer.cpp: Peer.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Peer.h -o temp/unix-debug/moc_Peer.cpp

temp/unix-debug/moc_Net.cpp: Peer.h \
		Net.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Net.h -o temp/unix-debug/moc_Net.cpp

temp/unix-debug/moc_Settings.cpp: Settings.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Settings.h -o temp/unix-debug/moc_Settings.cpp

temp/unix-debug/moc_InputAxisWidget.cpp: temp/unix-debug/ui_InputAxisWidget.h \
		InputAxisWidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) InputAxisWidget.h -o temp/unix-debug/moc_InputAxisWidget.cpp

temp/unix-debug/moc_InputBtnWidget.cpp: temp/unix-debug/ui_InputBtnWidget.h \
		InputBtnWidget.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) InputBtnWidget.h -o temp/unix-debug/moc_InputBtnWidget.cpp

temp/unix-debug/moc_Input.cpp: Input.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Input.h -o temp/unix-debug/moc_Input.cpp

temp/unix-debug/moc_InputDialog.cpp: InputAxisWidget.h \
		temp/unix-debug/ui_InputAxisWidget.h \
		InputBtnWidget.h \
		temp/unix-debug/ui_InputBtnWidget.h \
		InputDialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) InputDialog.h -o temp/unix-debug/moc_InputDialog.cpp

temp/unix-debug/moc_Inputs.cpp: Input.h \
		Inputs.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) Inputs.h -o temp/unix-debug/moc_Inputs.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: temp/unix-debug/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) temp/unix-debug/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: temp/unix-debug/ui_Window.h temp/unix-debug/ui_InputAxisWidget.h temp/unix-debug/ui_InputBtnWidget.h temp/unix-debug/ui_InputDialog.h
compiler_uic_clean:
	-$(DEL_FILE) temp/unix-debug/ui_Window.h temp/unix-debug/ui_InputAxisWidget.h temp/unix-debug/ui_InputBtnWidget.h temp/unix-debug/ui_InputDialog.h
temp/unix-debug/ui_Window.h: Window.ui
	/usr/bin/uic-qt4 Window.ui -o temp/unix-debug/ui_Window.h

temp/unix-debug/ui_InputAxisWidget.h: InputAxisWidget.ui
	/usr/bin/uic-qt4 InputAxisWidget.ui -o temp/unix-debug/ui_InputAxisWidget.h

temp/unix-debug/ui_InputBtnWidget.h: InputBtnWidget.ui
	/usr/bin/uic-qt4 InputBtnWidget.ui -o temp/unix-debug/ui_InputBtnWidget.h

temp/unix-debug/ui_InputDialog.h: InputDialog.ui
	/usr/bin/uic-qt4 InputDialog.ui -o temp/unix-debug/ui_InputDialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

temp/unix-debug/main.o: main.cpp Window.h \
		Net.h \
		Peer.h \
		Inputs.h \
		Input.h \
		Settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/unix-debug/main.o main.cpp

temp/unix-debug/Window.o: Window.cpp Window.h \
		temp/unix-debug/ui_Window.h \
		Net.h \
		Peer.h \
		Inputs.h \
		Input.h \
		InputDialog.h \
		InputAxisWidget.h \
		temp/unix-debug/ui_InputAxisWidget.h \
		InputBtnWidget.h \
		temp/unix-debug/ui_InputBtnWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/unix-debug/Window.o Window.cpp

temp/unix-debug/Peer.o: Peer.cpp Peer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/unix-debug/Peer.o Peer.cpp

temp/unix-debug/Net.o: Net.cpp Net.h \
		Peer.h \
		Settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/unix-debug/Net.o Net.cpp

temp/unix-debug/Settings.o: Settings.cpp Settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/unix-debug/Settings.o Settings.cpp

temp/unix-debug/Input.o: Input.cpp Input.h \
		Settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/unix-debug/Input.o Input.cpp

temp/unix-debug/InputDialog.o: InputDialog.cpp InputDialog.h \
		InputAxisWidget.h \
		temp/unix-debug/ui_InputAxisWidget.h \
		InputBtnWidget.h \
		temp/unix-debug/ui_InputBtnWidget.h \
		temp/unix-debug/ui_InputDialog.h \
		Inputs.h \
		Input.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/unix-debug/InputDialog.o InputDialog.cpp

temp/unix-debug/Inputs.o: Inputs.cpp Inputs.h \
		Input.h \
		Settings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/unix-debug/Inputs.o Inputs.cpp

temp/unix-debug/moc_Window.o: temp/unix-debug/moc_Window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/unix-debug/moc_Window.o temp/unix-debug/moc_Window.cpp

temp/unix-debug/moc_Peer.o: temp/unix-debug/moc_Peer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/unix-debug/moc_Peer.o temp/unix-debug/moc_Peer.cpp

temp/unix-debug/moc_Net.o: temp/unix-debug/moc_Net.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/unix-debug/moc_Net.o temp/unix-debug/moc_Net.cpp

temp/unix-debug/moc_Settings.o: temp/unix-debug/moc_Settings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/unix-debug/moc_Settings.o temp/unix-debug/moc_Settings.cpp

temp/unix-debug/moc_InputAxisWidget.o: temp/unix-debug/moc_InputAxisWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/unix-debug/moc_InputAxisWidget.o temp/unix-debug/moc_InputAxisWidget.cpp

temp/unix-debug/moc_InputBtnWidget.o: temp/unix-debug/moc_InputBtnWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/unix-debug/moc_InputBtnWidget.o temp/unix-debug/moc_InputBtnWidget.cpp

temp/unix-debug/moc_Input.o: temp/unix-debug/moc_Input.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/unix-debug/moc_Input.o temp/unix-debug/moc_Input.cpp

temp/unix-debug/moc_InputDialog.o: temp/unix-debug/moc_InputDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/unix-debug/moc_InputDialog.o temp/unix-debug/moc_InputDialog.cpp

temp/unix-debug/moc_Inputs.o: temp/unix-debug/moc_Inputs.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o temp/unix-debug/moc_Inputs.o temp/unix-debug/moc_Inputs.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

